--- 
framework: mocha
postMerge: 
  pattern: 
    - "test/**/*.spec.js"
postRun: 
  command: 
    - "node --version"  
preRun: 
  command: 
    - npm ci
preMerge: 
  pattern: 
    - "test/**/*.spec.js"

    
